/**
 * Curated Lucide icons for divisions (200), grouped by theme.
 * Keep in sync with CMS custom field `global::lucide-icon-name` and admin/web pickers.
 */
export const DIVISION_ICON_GROUPS = [
  {
    id: 'business',
    label: 'Business & finance',
    icons: [
      'Briefcase',
      'BarChart3',
      'PieChart',
      'TrendingUp',
      'TrendingDown',
      'CreditCard',
      'Wallet',
      'Banknote',
      'Coins',
      'Receipt',
      'PiggyBank',
      'Scale',
      'Calculator',
      'Store',
      'HandCoins',
      'BadgeDollarSign',
      'CircleDollarSign',
      'DollarSign',
      'Percent',
      'Landmark',
    ],
  },
  {
    id: 'buildings',
    label: 'Buildings & places',
    icons: [
      'Building',
      'Building2',
      'Home',
      'Factory',
      'Hospital',
      'Hotel',
      'School',
      'Church',
      'Warehouse',
      'Castle',
      'House',
      'Tent',
      'LandPlot',
      'Signpost',
      'DoorOpen',
      'Library',
      'Armchair',
      'Lamp',
      'Fan',
      'Blinds',
    ],
  },
  {
    id: 'energy',
    label: 'Energy & environment',
    icons: [
      'Fuel',
      'Gauge',
      'Droplets',
      'Zap',
      'Battery',
      'BatteryCharging',
      'Sun',
      'Sunrise',
      'Sunset',
      'Leaf',
      'Recycle',
      'Cloud',
      'CloudRain',
      'Wind',
      'Waves',
      'ThermometerSun',
      'Flame',
      'Snowflake',
      'Sprout',
      'TreePine',
    ],
  },
  {
    id: 'industry',
    label: 'Industry & tools',
    icons: [
      'HardHat',
      'Hammer',
      'Wrench',
      'Cog',
      'Anvil',
      'BrickWall',
      'Drill',
      'Ruler',
      'Construction',
      'Pickaxe',
      'Cone',
      'Cylinder',
      'Plug',
      'Cable',
      'EthernetPort',
      'Settings',
      'Network',
      'Cpu',
      'Server',
      'TowerControl',
    ],
  },
  {
    id: 'transport',
    label: 'Transport & logistics',
    icons: [
      'Truck',
      'Ship',
      'Plane',
      'Train',
      'Anchor',
      'Sailboat',
      'Car',
      'Bus',
      'Bike',
      'Container',
      'Forklift',
      'MapPin',
      'Map',
      'Navigation',
      'Compass',
      'Route',
      'ShipWheel',
      'Luggage',
      'Package',
      'Fence',
    ],
  },
  {
    id: 'people',
    label: 'People & community',
    icons: [
      'Users',
      'UserPlus',
      'UserCheck',
      'HeartHandshake',
      'Handshake',
      'Smile',
      'Baby',
      'Accessibility',
      'UserRound',
      'UsersRound',
      'Heart',
      'ThumbsUp',
      'ShieldCheck',
      'Award',
      'Medal',
      'Target',
      'Flag',
      'Star',
      'Sparkles',
      'Trees',
    ],
  },
  {
    id: 'communication',
    label: 'Communication & media',
    icons: [
      'Mail',
      'Phone',
      'MessageSquare',
      'Send',
      'Megaphone',
      'Mic',
      'Headphones',
      'Video',
      'Tv',
      'Newspaper',
      'Rss',
      'Radio',
      'Podcast',
      'Camera',
      'Image',
      'Film',
      'Smartphone',
      'Tablet',
      'Monitor',
      'Wifi',
    ],
  },
  {
    id: 'technology',
    label: 'Technology & data',
    icons: [
      'Database',
      'Code',
      'Binary',
      'Bot',
      'CircuitBoard',
      'Fingerprint',
      'QrCode',
      'Scan',
      'Webhook',
      'Layers',
      'LayoutGrid',
      'LayoutDashboard',
      'Globe',
      'Globe2',
      'Radar',
      'Satellite',
      'GitBranch',
      'FileText',
      'ClipboardList',
      'HardDrive',
    ],
  },
  {
    id: 'security',
    label: 'Security & trust',
    icons: [
      'Lock',
      'LockKeyhole',
      'Shield',
      'Eye',
      'EyeOff',
      'ScanFace',
      'Key',
      'Vault',
      'ShieldAlert',
      'ShieldQuestion',
      'OctagonAlert',
      'BadgeCheck',
      'CircleCheck',
      'AlertTriangle',
      'CheckCircle2',
      'Link',
      'Ban',
      'FileLock',
      'UserX',
      'ShieldOff',
    ],
  },
  {
    id: 'science',
    label: 'Science, health & lifestyle',
    icons: [
      'Stethoscope',
      'Microscope',
      'Atom',
      'FlaskConical',
      'Brain',
      'Dna',
      'Orbit',
      'Telescope',
      'Activity',
      'Pill',
      'Syringe',
      'Cross',
      'Bandage',
      'Ambulance',
      'BookOpen',
      'Coffee',
      'Gift',
      'Music',
      'Gamepad2',
      'Palette',
    ],
  },
] as const;

export type DivisionIconGroup = (typeof DIVISION_ICON_GROUPS)[number];
export type DivisionIconName = DivisionIconGroup['icons'][number];

export const DIVISION_ICON_NAMES: readonly DivisionIconName[] =
  DIVISION_ICON_GROUPS.flatMap(g => [...g.icons]);

const NAME_SET = new Set<string>(DIVISION_ICON_NAMES);

export function isDivisionIconName(value: string): value is DivisionIconName {
  return NAME_SET.has(value);
}
